{% set name = "intake-esm" %}
{% set version = "2019.5.11" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e307adf982f1729b09e24f828142a52398ba201f67b6bc636f1bb2bbe18c5fdb

build: 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  noarch: python

requirements:

  host:
    - python >3.5
    - pip
    - setuptools_scm
  


  run:
    - python >3.5
    - intake-xarray
    - tqdm

test:
  imports:
    - intake_esm

about:
  
  home: https://github.com/NCAR/intake-esm
  license: Apache
  license_file: LICENSE
  summary: |
    Intake-esm provides a plugin for building and loading intake catalogs for earth system data sets holdings, such as CMIP and CESM Large Ensemble datasets.  
  dev_url: https://github.com/NCAR/intake-esm
  doc_url: https://intake-esm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
    - jukent
    - kmpaul
