{% set name = "intake-esm" %}
{% set version = "2019.10.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 959625b6e20f3153a800a541bb4341ef11db6ca2c761e9e8f22b641349dd8c74

build: 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  noarch: python

requirements:

  host:
    - python >3.5
    - pip
    - setuptools_scm
  
  run:
    - python >3.5
    - intake-xarray >=0.3.1
    - fsspec
    - s3fs
    - gcsfs


test:
  imports:
    - intake_esm

about:
  
  home: https://github.com/NCAR/intake-esm
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    An intake plugin for parsing an ESM (Earth System Model) Collection/catalog and 
    loading assets (netCDF files and/or Zarr stores) into xarray data sets.
  dev_url: https://github.com/NCAR/intake-esm
  doc_url: https://intake-esm.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andersy005
    - matt-long
    - jukent
    - kmpaul
