travis:
  secure:
    BINSTAR_TOKEN: u3BM6Mgwhe7HtI+jDW0NT1vlRTfkPsdYiLM1mve7VHwQecWyCvKLhrNauFWka4/wTWg6wsyowwJmDq5vUo84O1dDsocu2uEEq7prhuNiwP5p9LTwfWlEk+cjxKrh/D2r+P2E7qibZFD2jk6Zy6LLgjNlNBV54ze5+ixx9WroVDgaxfWqRNI+3Wg559ZoDDgbBqDQzETfHE+OPcqgWdXf4mmi5jUNus/hF1n+8R4O4c2OnE53wDLbhEDjF32JrkNrrdEUo8uw7wGthiWzXh2RSZANSM+9lMIDhrbFAsmMxtsYChfaI88V5uPSXIn8HjFuC98zrME6M6oQGo/futH/g1JA2B52jTePriwMfjvMhT18Z3uf4SxvIo0lIgJjnG7dz7VnKJodSLpCMd15axzm+Cxg8y514BnkneaMNubv2p+Wg41fK3ahmXURZSzBollJkLMaAuT+3kECTPkcNZZSejPnHDN6mVIkbYYhTVkjQK0tRIWxAvOxePK7k5zzU2jZ5ggc+ZobmmnsxzhZC8qGe/KSp92ER5CnX0eQbNKHCS7AoNEFIKSXJmi9C8eG/AGXa5UPhiUG44Xy9m7OuqLTMZiMOSz+72k67hoCBZVNnq0JOXi9svIxT+jJuSOlWI8YL0vzZB+oQ3gRllIAzN3OgyvnYs2V1B9ko9umkar+CMg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
